FROM golang:1.14-alpine AS builder

LABEL maintainer="Alireza Josheghani <josheghani.dev@gmail.com>"

# Creating work directory
WORKDIR /app

# Adding project to work directory
ADD . /app

# build project
RUN go build -o server .

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/server /app

EXPOSE 3001
EXPOSE 3002

ENTRYPOINT ["/app/server"]
CMD ["--ug-port", "3001", "--tg-port", "3002"]