// Code generated by protoc-gen-go. DO NOT EDIT.
// source: friend.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Friend struct {
	FriendId             string               `protobuf:"bytes,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Accepted             bool                 `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Friend) Reset()         { *m = Friend{} }
func (m *Friend) String() string { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()    {}
func (*Friend) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{0}
}

func (m *Friend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friend.Unmarshal(m, b)
}
func (m *Friend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friend.Marshal(b, m, deterministic)
}
func (m *Friend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friend.Merge(m, src)
}
func (m *Friend) XXX_Size() int {
	return xxx_messageInfo_Friend.Size(m)
}
func (m *Friend) XXX_DiscardUnknown() {
	xxx_messageInfo_Friend.DiscardUnknown(m)
}

var xxx_messageInfo_Friend proto.InternalMessageInfo

func (m *Friend) GetFriendId() string {
	if m != nil {
		return m.FriendId
	}
	return ""
}

func (m *Friend) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Friend) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *Friend) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Friend) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Friend)(nil), "messages.Friend")
}

func init() { proto.RegisterFile("friend.proto", fileDescriptor_2b65cbc293af6bbd) }

var fileDescriptor_2b65cbc293af6bbd = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0xbd, 0x8e, 0x83, 0x30,
	0x10, 0x84, 0xe5, 0xfb, 0xe1, 0x8c, 0xef, 0x2a, 0x37, 0x87, 0x48, 0x11, 0x94, 0x8a, 0xca, 0x48,
	0x49, 0x95, 0x92, 0x26, 0x12, 0x2d, 0x4a, 0x8f, 0x0c, 0x5e, 0x10, 0x52, 0x88, 0x2d, 0x7b, 0x79,
	0xcf, 0x3c, 0x52, 0x84, 0x0d, 0x69, 0x53, 0xee, 0xcc, 0x7c, 0xab, 0x8f, 0xfd, 0xf5, 0x76, 0x84,
	0xbb, 0x12, 0xc6, 0x6a, 0xd4, 0x9c, 0x4e, 0xe0, 0x9c, 0x1c, 0xc0, 0xa5, 0xfb, 0x41, 0xeb, 0xe1,
	0x06, 0x85, 0xcf, 0xdb, 0xb9, 0x2f, 0x70, 0x9c, 0xc0, 0xa1, 0x9c, 0x4c, 0x98, 0x1e, 0x1e, 0x84,
	0x45, 0x17, 0xcf, 0xf2, 0x1d, 0x8b, 0xc3, 0x97, 0x66, 0x54, 0x09, 0xc9, 0x48, 0x1e, 0xd7, 0x34,
	0x04, 0x95, 0xe2, 0xff, 0xec, 0x67, 0x76, 0x60, 0x97, 0xea, 0xc3, 0x57, 0xd1, 0x72, 0x56, 0x8a,
	0xa7, 0x8c, 0xca, 0xae, 0x03, 0x83, 0xa0, 0x92, 0xcf, 0x8c, 0xe4, 0xb4, 0x7e, 0xdd, 0xfc, 0xcc,
	0x58, 0x67, 0x41, 0x22, 0xa8, 0x46, 0x62, 0xf2, 0x95, 0x91, 0xfc, 0xf7, 0x98, 0x8a, 0xa0, 0x24,
	0x36, 0x25, 0x71, 0xdd, 0x94, 0xea, 0x78, 0x5d, 0x97, 0xb8, 0xa0, 0xb3, 0x51, 0x1b, 0xfa, 0xfd,
	0x1e, 0x5d, 0xd7, 0x25, 0xb6, 0x91, 0xaf, 0x4f, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xd4,
	0x1f, 0x6c, 0x14, 0x01, 0x00, 0x00,
}
