// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Sender               *User                `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Reciever             *User                `protobuf:"bytes,4,opt,name=reciever,proto3" json:"reciever,omitempty"`
	Edited               bool                 `protobuf:"varint,5,opt,name=edited,proto3" json:"edited,omitempty"`
	Deleted              bool                 `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetSender() *User {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetReciever() *User {
	if m != nil {
		return m.Reciever
	}
	return nil
}

func (m *Message) GetEdited() bool {
	if m != nil {
		return m.Edited
	}
	return false
}

func (m *Message) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Message) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Message) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Message) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "messages.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xbd, 0x4e, 0xc4, 0x30,
	0x10, 0x84, 0x95, 0x00, 0xf9, 0x59, 0xc4, 0x15, 0x2e, 0x90, 0x95, 0x86, 0x88, 0x02, 0x45, 0x14,
	0x3e, 0x09, 0x2a, 0xca, 0x7b, 0x00, 0x9a, 0x08, 0x6a, 0x94, 0x8b, 0x97, 0xc8, 0xd2, 0x25, 0x8e,
	0xec, 0x0d, 0x0f, 0xcd, 0x53, 0x20, 0xff, 0x51, 0x9d, 0x74, 0x9d, 0x67, 0x67, 0x3e, 0xef, 0x0e,
	0xdc, 0xcd, 0x68, 0xed, 0x30, 0xa1, 0x58, 0x8d, 0x26, 0xcd, 0xaa, 0x28, 0x6d, 0xf3, 0x30, 0x69,
	0x3d, 0x9d, 0x70, 0xef, 0xe7, 0xc7, 0xed, 0x7b, 0x4f, 0x6a, 0x46, 0x4b, 0xc3, 0xbc, 0x86, 0x68,
	0x03, 0x9b, 0x45, 0x13, 0xde, 0x8f, 0xbf, 0x39, 0x94, 0xef, 0x81, 0x64, 0x3b, 0xc8, 0x95, 0xe4,
	0x59, 0x9b, 0x75, 0x75, 0x9f, 0x2b, 0xc9, 0x38, 0x94, 0xa3, 0x5e, 0x08, 0x17, 0xe2, 0xb9, 0x1f,
	0x26, 0xc9, 0x9e, 0xa0, 0xb0, 0xb8, 0x48, 0x34, 0xfc, 0xaa, 0xcd, 0xba, 0xdb, 0x97, 0x9d, 0x48,
	0xdb, 0xc5, 0xa7, 0x45, 0xd3, 0x47, 0x97, 0x3d, 0x43, 0x65, 0x70, 0x54, 0xf8, 0x83, 0x86, 0x5f,
	0x9f, 0x4d, 0xfe, 0xfb, 0xec, 0x1e, 0x0a, 0x94, 0x8a, 0x50, 0xf2, 0x9b, 0x36, 0xeb, 0xaa, 0x3e,
	0x2a, 0x77, 0x85, 0xc4, 0x13, 0x3a, 0xa3, 0xf0, 0x46, 0x92, 0xec, 0x0d, 0x60, 0x34, 0x38, 0x10,
	0xca, 0xaf, 0x81, 0x78, 0xe9, 0xff, 0x6f, 0x44, 0x68, 0x2f, 0x52, 0x7b, 0xf1, 0x91, 0xda, 0xf7,
	0x75, 0x4c, 0x1f, 0xc8, 0xa1, 0xdb, 0x2a, 0x13, 0x5a, 0x5d, 0x46, 0x63, 0x3a, 0xa0, 0xf1, 0x00,
	0x87, 0xd6, 0x97, 0xd1, 0x98, 0x3e, 0xd0, 0xb1, 0xf0, 0xf6, 0xeb, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x02, 0xc4, 0x64, 0x7c, 0xbb, 0x01, 0x00, 0x00,
}
