// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PERSONAL_STATE int32

const (
	PERSONAL_STATE_OFFLINE   PERSONAL_STATE = 0
	PERSONAL_STATE_ONLINE    PERSONAL_STATE = 1
	PERSONAL_STATE_IDLE      PERSONAL_STATE = 2
	PERSONAL_STATE_BUSY      PERSONAL_STATE = 3
	PERSONAL_STATE_INVISIBLE PERSONAL_STATE = 4
)

var PERSONAL_STATE_name = map[int32]string{
	0: "OFFLINE",
	1: "ONLINE",
	2: "IDLE",
	3: "BUSY",
	4: "INVISIBLE",
}

var PERSONAL_STATE_value = map[string]int32{
	"OFFLINE":   0,
	"ONLINE":    1,
	"IDLE":      2,
	"BUSY":      3,
	"INVISIBLE": 4,
}

func (x PERSONAL_STATE) String() string {
	return proto.EnumName(PERSONAL_STATE_name, int32(x))
}

func (PERSONAL_STATE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname             string               `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Username             string               `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Hash                 string               `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	IsActive             bool                 `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Avatar               string               `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Activity             int64                `protobuf:"varint,9,opt,name=activity,proto3" json:"activity,omitempty"`
	State                PERSONAL_STATE       `protobuf:"varint,10,opt,name=state,proto3,enum=messages.PERSONAL_STATE" json:"state,omitempty"`
	LastLogin            *timestamp.Timestamp `protobuf:"bytes,11,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	JoinedAt             *timestamp.Timestamp `protobuf:"bytes,12,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetActivity() int64 {
	if m != nil {
		return m.Activity
	}
	return 0
}

func (m *User) GetState() PERSONAL_STATE {
	if m != nil {
		return m.State
	}
	return PERSONAL_STATE_OFFLINE
}

func (m *User) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *User) GetJoinedAt() *timestamp.Timestamp {
	if m != nil {
		return m.JoinedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("messages.PERSONAL_STATE", PERSONAL_STATE_name, PERSONAL_STATE_value)
	proto.RegisterType((*User)(nil), "messages.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x50, 0x4d, 0xab, 0x9b, 0x40,
	0x14, 0xad, 0x1f, 0xf1, 0xe9, 0x4d, 0x5f, 0x90, 0xa1, 0x94, 0x21, 0x5d, 0x54, 0xba, 0x92, 0x2e,
	0x7c, 0xf0, 0xba, 0x28, 0x5d, 0xfa, 0xa8, 0x01, 0x41, 0x4c, 0xd1, 0xa4, 0xd0, 0x95, 0x4c, 0xea,
	0xc4, 0x4c, 0xd1, 0x28, 0xce, 0x98, 0xd2, 0xff, 0xd7, 0x1f, 0x56, 0x66, 0x26, 0x06, 0xba, 0xca,
	0xee, 0x9e, 0x73, 0xcf, 0xb9, 0x87, 0x7b, 0x00, 0x26, 0x4e, 0xc7, 0x68, 0x18, 0x7b, 0xd1, 0x23,
	0xb7, 0xa3, 0x9c, 0x93, 0x86, 0xf2, 0xf5, 0xfb, 0xa6, 0xef, 0x9b, 0x96, 0x3e, 0x29, 0xfe, 0x30,
	0x1d, 0x9f, 0x04, 0xeb, 0x28, 0x17, 0xa4, 0x1b, 0xb4, 0xf4, 0xc3, 0x5f, 0x0b, 0xec, 0x3d, 0xa7,
	0x23, 0x5a, 0x81, 0xc9, 0x6a, 0x6c, 0x04, 0x46, 0xe8, 0x15, 0x26, 0xab, 0xd1, 0x1a, 0xdc, 0xe3,
	0xd4, 0xb6, 0x67, 0xd2, 0x51, 0x6c, 0x2a, 0xf6, 0x86, 0xe5, 0x4e, 0xa6, 0xa9, 0x9d, 0xa5, 0x77,
	0x33, 0x46, 0x08, 0xec, 0x13, 0xe1, 0x27, 0x6c, 0x2b, 0x5e, 0xcd, 0xe8, 0x0d, 0x2c, 0x68, 0x47,
	0x58, 0x8b, 0x17, 0x8a, 0xd4, 0x40, 0x5e, 0x19, 0x08, 0xe7, 0xbf, 0xfb, 0xb1, 0xc6, 0x8e, 0xbe,
	0x32, 0x63, 0xf4, 0x0e, 0x3c, 0xc6, 0x2b, 0xf2, 0x53, 0xb0, 0x0b, 0xc5, 0x0f, 0x81, 0x11, 0xba,
	0x85, 0xcb, 0x78, 0xac, 0x30, 0x7a, 0x0b, 0x0e, 0xb9, 0x10, 0x41, 0x46, 0xec, 0x2a, 0xdb, 0x15,
	0xc9, 0x83, 0xca, 0xc1, 0xc4, 0x1f, 0xec, 0x05, 0x46, 0x68, 0x15, 0x37, 0x8c, 0x22, 0x58, 0x70,
	0x41, 0x04, 0xc5, 0x10, 0x18, 0xe1, 0xea, 0x19, 0x47, 0x73, 0x45, 0xd1, 0xb7, 0xa4, 0x28, 0xb7,
	0x79, 0x9c, 0x55, 0xe5, 0x2e, 0xde, 0x25, 0x85, 0x96, 0xa1, 0x2f, 0x00, 0x2d, 0xe1, 0xa2, 0x6a,
	0xfb, 0x86, 0x9d, 0xf1, 0x32, 0x30, 0xc2, 0xe5, 0xf3, 0x3a, 0xd2, 0x6d, 0x46, 0x73, 0x9b, 0xd1,
	0x6e, 0x6e, 0xb3, 0xf0, 0xa4, 0x3a, 0x93, 0x62, 0xf4, 0x19, 0xbc, 0x5f, 0x3d, 0x3b, 0xd3, 0xba,
	0x22, 0x02, 0xbf, 0xbe, 0xeb, 0x74, 0xb5, 0x38, 0x16, 0x32, 0x73, 0x1a, 0x6a, 0x22, 0xb4, 0xf3,
	0xf1, 0x7e, 0xe6, 0x55, 0x1d, 0x8b, 0x8f, 0x19, 0xac, 0xfe, 0xff, 0x03, 0x2d, 0xe1, 0x61, 0xbb,
	0xd9, 0x64, 0x69, 0x9e, 0xf8, 0xaf, 0x10, 0x80, 0xb3, 0xcd, 0xd5, 0x6c, 0x20, 0x17, 0xec, 0xf4,
	0x6b, 0x96, 0xf8, 0xa6, 0x9c, 0x5e, 0xf6, 0xe5, 0x0f, 0xdf, 0x42, 0x8f, 0xe0, 0xa5, 0xf9, 0xf7,
	0xb4, 0x4c, 0x5f, 0xb2, 0xc4, 0xb7, 0x0f, 0x8e, 0x0a, 0xfb, 0xf4, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x52, 0x3b, 0xb2, 0x8b, 0x54, 0x02, 0x00, 0x00,
}
