// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogOnEvent struct {
	Username             []byte   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token                []byte   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogOnEvent) Reset()         { *m = LogOnEvent{} }
func (m *LogOnEvent) String() string { return proto.CompactTextString(m) }
func (*LogOnEvent) ProtoMessage()    {}
func (*LogOnEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *LogOnEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogOnEvent.Unmarshal(m, b)
}
func (m *LogOnEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogOnEvent.Marshal(b, m, deterministic)
}
func (m *LogOnEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogOnEvent.Merge(m, src)
}
func (m *LogOnEvent) XXX_Size() int {
	return xxx_messageInfo_LogOnEvent.Size(m)
}
func (m *LogOnEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LogOnEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LogOnEvent proto.InternalMessageInfo

func (m *LogOnEvent) GetUsername() []byte {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *LogOnEvent) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *LogOnEvent) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type TheaterLogOnEvent struct {
	Room                 []byte   `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Token                []byte   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TheaterLogOnEvent) Reset()         { *m = TheaterLogOnEvent{} }
func (m *TheaterLogOnEvent) String() string { return proto.CompactTextString(m) }
func (*TheaterLogOnEvent) ProtoMessage()    {}
func (*TheaterLogOnEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *TheaterLogOnEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TheaterLogOnEvent.Unmarshal(m, b)
}
func (m *TheaterLogOnEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TheaterLogOnEvent.Marshal(b, m, deterministic)
}
func (m *TheaterLogOnEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TheaterLogOnEvent.Merge(m, src)
}
func (m *TheaterLogOnEvent) XXX_Size() int {
	return xxx_messageInfo_TheaterLogOnEvent.Size(m)
}
func (m *TheaterLogOnEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TheaterLogOnEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TheaterLogOnEvent proto.InternalMessageInfo

func (m *TheaterLogOnEvent) GetRoom() []byte {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *TheaterLogOnEvent) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*LogOnEvent)(nil), "protobuf.LogOnEvent")
	proto.RegisterType((*TheaterLogOnEvent)(nil), "protobuf.TheaterLogOnEvent")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0x51, 0x5c,
	0x5c, 0x3e, 0xf9, 0xe9, 0xfe, 0x79, 0xae, 0x65, 0xa9, 0x79, 0x25, 0x42, 0x52, 0x5c, 0x1c, 0xa5,
	0xc5, 0xa9, 0x45, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x70, 0x3e,
	0x48, 0xae, 0x20, 0xb1, 0xb8, 0xb8, 0x3c, 0xbf, 0x28, 0x45, 0x82, 0x09, 0x22, 0x07, 0xe3, 0x0b,
	0x89, 0x70, 0xb1, 0x96, 0xe4, 0x67, 0xa7, 0xe6, 0x49, 0x30, 0x83, 0x25, 0x20, 0x1c, 0x25, 0x5b,
	0x2e, 0xc1, 0x90, 0x8c, 0xd4, 0xc4, 0x92, 0xd4, 0x22, 0x24, 0x2b, 0x84, 0xb8, 0x58, 0x8a, 0xf2,
	0xf3, 0x73, 0xa1, 0xc6, 0x83, 0xd9, 0x08, 0xed, 0x4c, 0x48, 0xda, 0x93, 0xd8, 0xc0, 0x8e, 0x34,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xb5, 0xe0, 0xb7, 0xb9, 0x00, 0x00, 0x00,
}
