// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package protobuf

import (
	enums "movie.night.ws.server/hub/protocol/protobuf/enums"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CMsgProtoBufHeader struct {
	UserHash             []byte   `protobuf:"bytes,1,opt,name=UserHash,proto3" json:"UserHash,omitempty"`
	IpAddr               []byte   `protobuf:"bytes,2,opt,name=IpAddr,proto3" json:"IpAddr,omitempty"`
	SessionClientId      int32    `protobuf:"varint,3,opt,name=SessionClientId,proto3" json:"SessionClientId,omitempty"`
	AuthToken            []byte   `protobuf:"bytes,4,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgProtoBufHeader) Reset()         { *m = CMsgProtoBufHeader{} }
func (m *CMsgProtoBufHeader) String() string { return proto.CompactTextString(m) }
func (*CMsgProtoBufHeader) ProtoMessage()    {}
func (*CMsgProtoBufHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *CMsgProtoBufHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgProtoBufHeader.Unmarshal(m, b)
}
func (m *CMsgProtoBufHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgProtoBufHeader.Marshal(b, m, deterministic)
}
func (m *CMsgProtoBufHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgProtoBufHeader.Merge(m, src)
}
func (m *CMsgProtoBufHeader) XXX_Size() int {
	return xxx_messageInfo_CMsgProtoBufHeader.Size(m)
}
func (m *CMsgProtoBufHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgProtoBufHeader.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgProtoBufHeader proto.InternalMessageInfo

func (m *CMsgProtoBufHeader) GetUserHash() []byte {
	if m != nil {
		return m.UserHash
	}
	return nil
}

func (m *CMsgProtoBufHeader) GetIpAddr() []byte {
	if m != nil {
		return m.IpAddr
	}
	return nil
}

func (m *CMsgProtoBufHeader) GetSessionClientId() int32 {
	if m != nil {
		return m.SessionClientId
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetAuthToken() []byte {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

type MsgEvent struct {
	Type                 enums.EMSG           `protobuf:"varint,1,opt,name=type,proto3,enum=enums.EMSG" json:"type,omitempty"`
	Data                 []byte               `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MsgEvent) Reset()         { *m = MsgEvent{} }
func (m *MsgEvent) String() string { return proto.CompactTextString(m) }
func (*MsgEvent) ProtoMessage()    {}
func (*MsgEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *MsgEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgEvent.Unmarshal(m, b)
}
func (m *MsgEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgEvent.Marshal(b, m, deterministic)
}
func (m *MsgEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEvent.Merge(m, src)
}
func (m *MsgEvent) XXX_Size() int {
	return xxx_messageInfo_MsgEvent.Size(m)
}
func (m *MsgEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEvent proto.InternalMessageInfo

func (m *MsgEvent) GetType() enums.EMSG {
	if m != nil {
		return m.Type
	}
	return enums.EMSG_INVALID
}

func (m *MsgEvent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MsgEvent) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CMsgProtoBufHeader)(nil), "protobuf.CMsgProtoBufHeader")
	proto.RegisterType((*MsgEvent)(nil), "protobuf.MsgEvent")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xa9, 0xd6, 0xd1, 0xbd, 0x89, 0xe2, 0x3b, 0x48, 0x29, 0xc2, 0xc6, 0x4e, 0x3d, 0xb5,
	0x30, 0x4f, 0x1e, 0xeb, 0x18, 0x6e, 0x87, 0x82, 0x74, 0xf3, 0x2c, 0xa9, 0x79, 0xeb, 0x8a, 0x6b,
	0x53, 0x92, 0x57, 0x41, 0xff, 0x0a, 0xff, 0x64, 0x31, 0x6d, 0x15, 0x76, 0x49, 0xf2, 0xfd, 0x41,
	0xf8, 0xf0, 0x05, 0xc8, 0x85, 0xa1, 0xa8, 0xd1, 0x8a, 0x15, 0x7a, 0xf6, 0xca, 0xdb, 0x7d, 0x30,
	0x2d, 0x94, 0x2a, 0x8e, 0x14, 0x0f, 0x46, 0xcc, 0x65, 0x45, 0x86, 0x45, 0xd5, 0x74, 0xd5, 0xe0,
	0x86, 0xea, 0xb6, 0x32, 0xb1, 0x3d, 0x3b, 0x6b, 0xfe, 0xed, 0x00, 0x2e, 0x53, 0x53, 0x3c, 0xff,
	0xaa, 0xc7, 0x76, 0xbf, 0x26, 0x21, 0x49, 0x63, 0x00, 0xde, 0x8b, 0x21, 0xbd, 0x16, 0xe6, 0xe0,
	0x3b, 0x33, 0x27, 0xbc, 0xcc, 0xfe, 0x34, 0xde, 0xc2, 0x68, 0xd3, 0x24, 0x52, 0x6a, 0xff, 0xcc,
	0x26, 0xbd, 0xc2, 0x10, 0xae, 0xb7, 0x64, 0x4c, 0xa9, 0xea, 0xe5, 0xb1, 0xa4, 0x9a, 0x37, 0xd2,
	0x3f, 0x9f, 0x39, 0xe1, 0x45, 0x76, 0x6a, 0xe3, 0x1d, 0x8c, 0x93, 0x96, 0x0f, 0x3b, 0xf5, 0x4e,
	0xb5, 0xef, 0xda, 0x4f, 0xfe, 0x8d, 0xf9, 0x17, 0x78, 0xa9, 0x29, 0x56, 0x1f, 0x54, 0x33, 0x4e,
	0xc1, 0xe5, 0xcf, 0x86, 0x2c, 0xc3, 0xd5, 0x62, 0x12, 0x75, 0xe8, 0xab, 0x74, 0xfb, 0x94, 0xd9,
	0x00, 0x11, 0x5c, 0x29, 0x58, 0xf4, 0x28, 0xf6, 0x8d, 0x0f, 0x00, 0x6f, 0x9a, 0x04, 0x93, 0x7c,
	0x15, 0x6c, 0x19, 0x26, 0x8b, 0x20, 0xea, 0xc6, 0x89, 0x86, 0x71, 0xa2, 0xdd, 0x30, 0x4e, 0x36,
	0xee, 0xdb, 0x09, 0xe7, 0x23, 0x1b, 0xdf, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x4e, 0x97,
	0x9d, 0x61, 0x01, 0x00, 0x00,
}
