// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChatMsgEvent struct {
	Message              []byte               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	From                 string               `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string               `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Emojies              []uint64             `protobuf:"varint,4,rep,packed,name=emojies,proto3" json:"emojies,omitempty"`
	Mentions             []uint64             `protobuf:"varint,5,rep,packed,name=mentions,proto3" json:"mentions,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChatMsgEvent) Reset()         { *m = ChatMsgEvent{} }
func (m *ChatMsgEvent) String() string { return proto.CompactTextString(m) }
func (*ChatMsgEvent) ProtoMessage()    {}
func (*ChatMsgEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *ChatMsgEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMsgEvent.Unmarshal(m, b)
}
func (m *ChatMsgEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMsgEvent.Marshal(b, m, deterministic)
}
func (m *ChatMsgEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMsgEvent.Merge(m, src)
}
func (m *ChatMsgEvent) XXX_Size() int {
	return xxx_messageInfo_ChatMsgEvent.Size(m)
}
func (m *ChatMsgEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMsgEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMsgEvent proto.InternalMessageInfo

func (m *ChatMsgEvent) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ChatMsgEvent) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ChatMsgEvent) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ChatMsgEvent) GetEmojies() []uint64 {
	if m != nil {
		return m.Emojies
	}
	return nil
}

func (m *ChatMsgEvent) GetMentions() []uint64 {
	if m != nil {
		return m.Mentions
	}
	return nil
}

func (m *ChatMsgEvent) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*ChatMsgEvent)(nil), "protobuf.ChatMsgEvent")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xb1, 0x4e, 0xc4, 0x30,
	0x10, 0x44, 0xe5, 0x5c, 0x38, 0xee, 0x96, 0x13, 0x85, 0x2b, 0x2b, 0x0d, 0x16, 0x95, 0x2b, 0x47,
	0x82, 0x8a, 0x12, 0x21, 0x4a, 0x1a, 0x8b, 0x1e, 0x39, 0x61, 0xe3, 0x04, 0xe1, 0x6c, 0x14, 0x2f,
	0xfc, 0x1d, 0xff, 0x86, 0x70, 0xf0, 0x55, 0xf6, 0x9b, 0x99, 0x95, 0x1e, 0x40, 0x3f, 0x7a, 0xb6,
	0xcb, 0x4a, 0x4c, 0xf2, 0x90, 0x9f, 0xee, 0x6b, 0x68, 0x6e, 0x02, 0x51, 0xf8, 0xc4, 0xb6, 0x04,
	0x2d, 0x4f, 0x11, 0x13, 0xfb, 0xb8, 0x6c, 0xd3, 0xdb, 0x1f, 0x01, 0xa7, 0xa7, 0xd1, 0xf3, 0x4b,
	0x0a, 0xcf, 0xdf, 0x38, 0xb3, 0x54, 0x70, 0x19, 0x31, 0x25, 0x1f, 0x50, 0x09, 0x2d, 0xcc, 0xc9,
	0x15, 0x94, 0x12, 0xea, 0x61, 0xa5, 0xa8, 0x2a, 0x2d, 0xcc, 0xd1, 0xe5, 0xbf, 0xbc, 0x86, 0x8a,
	0x49, 0xed, 0x72, 0x52, 0x31, 0xfd, 0x5d, 0x63, 0xa4, 0x8f, 0x09, 0x93, 0xaa, 0xf5, 0xce, 0xd4,
	0xae, 0xa0, 0x6c, 0xe0, 0x10, 0x71, 0xe6, 0x89, 0xe6, 0xa4, 0x2e, 0x72, 0x75, 0x66, 0xf9, 0x00,
	0xd0, 0xaf, 0xe8, 0x19, 0xdf, 0xdf, 0x3c, 0xab, 0xbd, 0x16, 0xe6, 0xea, 0xae, 0xb1, 0x9b, 0xba,
	0x2d, 0xea, 0xf6, 0xb5, 0xa8, 0xbb, 0xe3, 0xff, 0xfa, 0x91, 0xbb, 0x7d, 0xae, 0xef, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x59, 0x2a, 0x61, 0xea, 0xff, 0x00, 0x00, 0x00,
}
