// Code generated by protoc-gen-go. DO NOT EDIT.
// source: members.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	messages "github.com/CastyLab/grpc.proto/messages"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TheaterMembers struct {
	Members              []*messages.User `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TheaterMembers) Reset()         { *m = TheaterMembers{} }
func (m *TheaterMembers) String() string { return proto.CompactTextString(m) }
func (*TheaterMembers) ProtoMessage()    {}
func (*TheaterMembers) Descriptor() ([]byte, []int) {
	return fileDescriptor_a130ba3d4c49b931, []int{0}
}

func (m *TheaterMembers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TheaterMembers.Unmarshal(m, b)
}
func (m *TheaterMembers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TheaterMembers.Marshal(b, m, deterministic)
}
func (m *TheaterMembers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TheaterMembers.Merge(m, src)
}
func (m *TheaterMembers) XXX_Size() int {
	return xxx_messageInfo_TheaterMembers.Size(m)
}
func (m *TheaterMembers) XXX_DiscardUnknown() {
	xxx_messageInfo_TheaterMembers.DiscardUnknown(m)
}

var xxx_messageInfo_TheaterMembers proto.InternalMessageInfo

func (m *TheaterMembers) GetMembers() []*messages.User {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*TheaterMembers)(nil), "protobuf.TheaterMembers")
}

func init() {
	proto.RegisterFile("members.proto", fileDescriptor_a130ba3d4c49b931)
}

var fileDescriptor_a130ba3d4c49b931 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0xcd, 0x4d,
	0x4a, 0x2d, 0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69,
	0x52, 0xc2, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0xc5, 0xfa, 0xa5, 0xc5, 0xa9, 0x45, 0x10,
	0x69, 0x25, 0x2b, 0x2e, 0xbe, 0x90, 0x8c, 0xd4, 0xc4, 0x92, 0xd4, 0x22, 0x5f, 0x88, 0x36, 0x21,
	0x0d, 0x2e, 0x76, 0xa8, 0x09, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x7c, 0x7a, 0x30, 0x8d,
	0x7a, 0xa1, 0xc5, 0xa9, 0x45, 0x41, 0x30, 0xe9, 0x24, 0x36, 0xb0, 0x11, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xcd, 0x62, 0xe0, 0xe0, 0x72, 0x00, 0x00, 0x00,
}
