// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	messages "github.com/CastyLab/grpc.proto/messages"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotificationMsgEvent struct {
	Notification         *messages.Notification `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *NotificationMsgEvent) Reset()         { *m = NotificationMsgEvent{} }
func (m *NotificationMsgEvent) String() string { return proto.CompactTextString(m) }
func (*NotificationMsgEvent) ProtoMessage()    {}
func (*NotificationMsgEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0}
}

func (m *NotificationMsgEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationMsgEvent.Unmarshal(m, b)
}
func (m *NotificationMsgEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationMsgEvent.Marshal(b, m, deterministic)
}
func (m *NotificationMsgEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationMsgEvent.Merge(m, src)
}
func (m *NotificationMsgEvent) XXX_Size() int {
	return xxx_messageInfo_NotificationMsgEvent.Size(m)
}
func (m *NotificationMsgEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationMsgEvent.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationMsgEvent proto.InternalMessageInfo

func (m *NotificationMsgEvent) GetNotification() *messages.Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

func init() {
	proto.RegisterType((*NotificationMsgEvent)(nil), "protobuf.NotificationMsgEvent")
}

func init() {
	proto.RegisterFile("notification.proto", fileDescriptor_736a457d4a5efa07)
}

var fileDescriptor_736a457d4a5efa07 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xcb, 0x2f, 0xc9,
	0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x00, 0x53, 0x49, 0xa5, 0x69, 0x52, 0xd2, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0xc5, 0xfa,
	0x98, 0xca, 0x94, 0x82, 0xb8, 0x44, 0xfc, 0x90, 0x44, 0x7d, 0x8b, 0xd3, 0x5d, 0xcb, 0x52, 0xf3,
	0x4a, 0x84, 0xac, 0xb8, 0x78, 0x90, 0x55, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0xe9,
	0xc1, 0xcc, 0xd2, 0x43, 0xd6, 0x15, 0x84, 0xa2, 0x36, 0x89, 0x0d, 0x6c, 0xb4, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xa4, 0x9a, 0xc1, 0x11, 0x97, 0x00, 0x00, 0x00,
}
