// Code generated by protoc-gen-go. DO NOT EDIT.
// source: state.proto

package protobuf

import (
	enums "github.com/CastyLab/gateway.server/hub/protocol/protobuf/enums"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	messages "github.com/CastyLab/grpc.proto/messages"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PersonalStateMsgEvent struct {
	User                 *messages.User            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	State                enums.EMSG_PERSONAL_STATE `protobuf:"varint,2,opt,name=state,proto3,enum=enums.EMSG_PERSONAL_STATE" json:"state,omitempty"`
	Activity             *messages.Activity        `protobuf:"bytes,3,opt,name=activity,proto3" json:"activity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PersonalStateMsgEvent) Reset()         { *m = PersonalStateMsgEvent{} }
func (m *PersonalStateMsgEvent) String() string { return proto.CompactTextString(m) }
func (*PersonalStateMsgEvent) ProtoMessage()    {}
func (*PersonalStateMsgEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{0}
}

func (m *PersonalStateMsgEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonalStateMsgEvent.Unmarshal(m, b)
}
func (m *PersonalStateMsgEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonalStateMsgEvent.Marshal(b, m, deterministic)
}
func (m *PersonalStateMsgEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonalStateMsgEvent.Merge(m, src)
}
func (m *PersonalStateMsgEvent) XXX_Size() int {
	return xxx_messageInfo_PersonalStateMsgEvent.Size(m)
}
func (m *PersonalStateMsgEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonalStateMsgEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PersonalStateMsgEvent proto.InternalMessageInfo

func (m *PersonalStateMsgEvent) GetUser() *messages.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PersonalStateMsgEvent) GetState() enums.EMSG_PERSONAL_STATE {
	if m != nil {
		return m.State
	}
	return enums.EMSG_PERSONAL_STATE_OFFLINE
}

func (m *PersonalStateMsgEvent) GetActivity() *messages.Activity {
	if m != nil {
		return m.Activity
	}
	return nil
}

type PersonalActivityMsgEvent struct {
	User                 *messages.User     `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Activity             *messages.Activity `protobuf:"bytes,2,opt,name=activity,proto3" json:"activity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PersonalActivityMsgEvent) Reset()         { *m = PersonalActivityMsgEvent{} }
func (m *PersonalActivityMsgEvent) String() string { return proto.CompactTextString(m) }
func (*PersonalActivityMsgEvent) ProtoMessage()    {}
func (*PersonalActivityMsgEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a888679467bb7853, []int{1}
}

func (m *PersonalActivityMsgEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonalActivityMsgEvent.Unmarshal(m, b)
}
func (m *PersonalActivityMsgEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonalActivityMsgEvent.Marshal(b, m, deterministic)
}
func (m *PersonalActivityMsgEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonalActivityMsgEvent.Merge(m, src)
}
func (m *PersonalActivityMsgEvent) XXX_Size() int {
	return xxx_messageInfo_PersonalActivityMsgEvent.Size(m)
}
func (m *PersonalActivityMsgEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonalActivityMsgEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PersonalActivityMsgEvent proto.InternalMessageInfo

func (m *PersonalActivityMsgEvent) GetUser() *messages.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PersonalActivityMsgEvent) GetActivity() *messages.Activity {
	if m != nil {
		return m.Activity
	}
	return nil
}

func init() {
	proto.RegisterType((*PersonalStateMsgEvent)(nil), "protobuf.PersonalStateMsgEvent")
	proto.RegisterType((*PersonalActivityMsgEvent)(nil), "protobuf.PersonalActivityMsgEvent")
}

func init() { proto.RegisterFile("state.proto", fileDescriptor_a888679467bb7853) }

var fileDescriptor_a888679467bb7853 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2e, 0x49, 0x2c,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x52, 0x82,
	0xa9, 0x79, 0xa5, 0xb9, 0xc5, 0xfa, 0x60, 0x12, 0x22, 0x29, 0x25, 0x9c, 0x9b, 0x5a, 0x5c, 0x9c,
	0x98, 0x9e, 0x5a, 0xac, 0x5f, 0x5a, 0x9c, 0x5a, 0x04, 0x11, 0x54, 0x9a, 0xcb, 0xc8, 0x25, 0x1a,
	0x90, 0x5a, 0x54, 0x9c, 0x9f, 0x97, 0x98, 0x13, 0x0c, 0x32, 0xc9, 0xb7, 0x38, 0xdd, 0xb5, 0x2c,
	0x35, 0xaf, 0x44, 0x48, 0x89, 0x8b, 0x05, 0xa4, 0x4e, 0x82, 0x51, 0x81, 0x51, 0x83, 0xdb, 0x88,
	0x4f, 0x0f, 0xa6, 0x5b, 0x2f, 0xb4, 0x38, 0xb5, 0x28, 0x08, 0x2c, 0x27, 0x64, 0xc0, 0xc5, 0x0a,
	0xb6, 0x5e, 0x82, 0x49, 0x81, 0x51, 0x83, 0xcf, 0x48, 0x4a, 0x0f, 0x62, 0x9f, 0xab, 0x6f, 0xb0,
	0x7b, 0x7c, 0x80, 0x6b, 0x50, 0xb0, 0xbf, 0x9f, 0xa3, 0x4f, 0x7c, 0x70, 0x88, 0x63, 0x88, 0x6b,
	0x10, 0x44, 0xa1, 0x90, 0x1e, 0x17, 0x47, 0x62, 0x72, 0x49, 0x66, 0x59, 0x66, 0x49, 0xa5, 0x04,
	0x33, 0xd8, 0x64, 0x21, 0x84, 0xc9, 0x8e, 0x50, 0x99, 0x20, 0xb8, 0x1a, 0xa5, 0x3c, 0x2e, 0x09,
	0x98, 0xf3, 0x60, 0xb2, 0x24, 0xb9, 0x10, 0xd9, 0x3e, 0x26, 0xc2, 0xf6, 0x25, 0xb1, 0x81, 0x83,
	0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x70, 0x25, 0x86, 0xcc, 0x57, 0x01, 0x00, 0x00,
}
