// Code generated by protoc-gen-go. DO NOT EDIT.
// source: theater.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TheaterVideoPlayer struct {
	TheaterId            string               `protobuf:"bytes,1,opt,name=theater_id,json=theaterId,proto3" json:"theater_id,omitempty"`
	Source               string               `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Poster               string               `protobuf:"bytes,3,opt,name=poster,proto3" json:"poster,omitempty"`
	CurrentTime          float32              `protobuf:"fixed32,4,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	UserId               string               `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SentAt               *timestamp.Timestamp `protobuf:"bytes,6,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TheaterVideoPlayer) Reset()         { *m = TheaterVideoPlayer{} }
func (m *TheaterVideoPlayer) String() string { return proto.CompactTextString(m) }
func (*TheaterVideoPlayer) ProtoMessage()    {}
func (*TheaterVideoPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ca216068025a679, []int{0}
}

func (m *TheaterVideoPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TheaterVideoPlayer.Unmarshal(m, b)
}
func (m *TheaterVideoPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TheaterVideoPlayer.Marshal(b, m, deterministic)
}
func (m *TheaterVideoPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TheaterVideoPlayer.Merge(m, src)
}
func (m *TheaterVideoPlayer) XXX_Size() int {
	return xxx_messageInfo_TheaterVideoPlayer.Size(m)
}
func (m *TheaterVideoPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_TheaterVideoPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_TheaterVideoPlayer proto.InternalMessageInfo

func (m *TheaterVideoPlayer) GetTheaterId() string {
	if m != nil {
		return m.TheaterId
	}
	return ""
}

func (m *TheaterVideoPlayer) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *TheaterVideoPlayer) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *TheaterVideoPlayer) GetCurrentTime() float32 {
	if m != nil {
		return m.CurrentTime
	}
	return 0
}

func (m *TheaterVideoPlayer) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TheaterVideoPlayer) GetSentAt() *timestamp.Timestamp {
	if m != nil {
		return m.SentAt
	}
	return nil
}

func init() {
	proto.RegisterType((*TheaterVideoPlayer)(nil), "protobuf.TheaterVideoPlayer")
}

func init() {
	proto.RegisterFile("theater.proto", fileDescriptor_9ca216068025a679)
}

var fileDescriptor_9ca216068025a679 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xc1, 0x4e, 0xc4, 0x20,
	0x18, 0x84, 0xc3, 0xaa, 0xac, 0xfb, 0xaf, 0x5e, 0x38, 0x28, 0xd9, 0xc4, 0x58, 0x3d, 0xf5, 0xc4,
	0x26, 0xee, 0x13, 0x78, 0xdc, 0x9b, 0x69, 0x1a, 0xaf, 0x1b, 0x5a, 0x7e, 0x2b, 0x49, 0x2b, 0x0d,
	0xfc, 0x1c, 0x7c, 0x4f, 0x1f, 0xc8, 0x50, 0xe8, 0x89, 0xcc, 0x37, 0x33, 0xc0, 0xc0, 0x3d, 0x7d,
	0xa3, 0x26, 0xf4, 0x6a, 0xf6, 0x8e, 0x9c, 0xb8, 0x5d, 0x8e, 0x2e, 0x7e, 0x1d, 0x9e, 0x07, 0xe7,
	0x86, 0x11, 0x8f, 0x2b, 0x38, 0x92, 0x9d, 0x30, 0x90, 0x9e, 0xe6, 0x1c, 0x7d, 0xfd, 0x63, 0x20,
	0xda, 0x5c, 0xfe, 0xb4, 0x06, 0xdd, 0xc7, 0xa8, 0x7f, 0xd1, 0x8b, 0x27, 0x80, 0x72, 0xe5, 0xc5,
	0x1a, 0xc9, 0x2a, 0x56, 0xef, 0x9a, 0x5d, 0x21, 0x67, 0x23, 0x1e, 0x80, 0x07, 0x17, 0x7d, 0x8f,
	0x72, 0xb3, 0x58, 0x45, 0x25, 0x3e, 0xbb, 0x40, 0xe8, 0xe5, 0x55, 0xe6, 0x59, 0x89, 0x17, 0xb8,
	0xeb, 0xa3, 0xf7, 0xf8, 0x43, 0x97, 0xf4, 0x01, 0x79, 0x5d, 0xb1, 0x7a, 0xd3, 0xec, 0x0b, 0x6b,
	0xed, 0x84, 0xe2, 0x11, 0xb6, 0x31, 0xe4, 0xe7, 0x6e, 0x72, 0x37, 0xc9, 0xb3, 0x11, 0x27, 0xd8,
	0x86, 0x54, 0xd4, 0x24, 0x79, 0xc5, 0xea, 0xfd, 0xdb, 0x41, 0xe5, 0x51, 0x6a, 0x1d, 0xa5, 0xda,
	0x75, 0x54, 0xc3, 0x53, 0xf4, 0x9d, 0x3a, 0xbe, 0x78, 0xa7, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x93, 0x10, 0xd6, 0x95, 0x19, 0x01, 0x00, 0x00,
}
