// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Pass                 string   `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf6805fbee998eb, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *AuthRequest) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

type ValidationError struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Errors               []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationError) Reset()         { *m = ValidationError{} }
func (m *ValidationError) String() string { return proto.CompactTextString(m) }
func (*ValidationError) ProtoMessage()    {}
func (*ValidationError) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf6805fbee998eb, []int{1}
}

func (m *ValidationError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationError.Unmarshal(m, b)
}
func (m *ValidationError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationError.Marshal(b, m, deterministic)
}
func (m *ValidationError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationError.Merge(m, src)
}
func (m *ValidationError) XXX_Size() int {
	return xxx_messageInfo_ValidationError.Size(m)
}
func (m *ValidationError) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationError.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationError proto.InternalMessageInfo

func (m *ValidationError) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ValidationError) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type AuthResponse struct {
	Code                 int64              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string             `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Token                []byte             `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Type                 string             `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Message              string             `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	RefreshedToken       []byte             `protobuf:"bytes,6,opt,name=refreshed_token,json=refreshedToken,proto3" json:"refreshed_token,omitempty"`
	ValidationError      []*ValidationError `protobuf:"bytes,7,rep,name=validation_error,json=validationError,proto3" json:"validation_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf6805fbee998eb, []int{2}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AuthResponse) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *AuthResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AuthResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AuthResponse) GetRefreshedToken() []byte {
	if m != nil {
		return m.RefreshedToken
	}
	return nil
}

func (m *AuthResponse) GetValidationError() []*ValidationError {
	if m != nil {
		return m.ValidationError
	}
	return nil
}

type RefreshTokenRequest struct {
	RefreshedToken       []byte   `protobuf:"bytes,2,opt,name=refreshed_token,json=refreshedToken,proto3" json:"refreshed_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRequest) Reset()         { *m = RefreshTokenRequest{} }
func (m *RefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRequest) ProtoMessage()    {}
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0bf6805fbee998eb, []int{3}
}

func (m *RefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRequest.Unmarshal(m, b)
}
func (m *RefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRequest.Merge(m, src)
}
func (m *RefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRequest.Size(m)
}
func (m *RefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRequest proto.InternalMessageInfo

func (m *RefreshTokenRequest) GetRefreshedToken() []byte {
	if m != nil {
		return m.RefreshedToken
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "proto.AuthRequest")
	proto.RegisterType((*ValidationError)(nil), "proto.ValidationError")
	proto.RegisterType((*AuthResponse)(nil), "proto.AuthResponse")
	proto.RegisterType((*RefreshTokenRequest)(nil), "proto.RefreshTokenRequest")
}

func init() { proto.RegisterFile("auth.service.proto", fileDescriptor_0bf6805fbee998eb) }

var fileDescriptor_0bf6805fbee998eb = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x4d, 0x29, 0x1f, 0x61, 0x20, 0x62, 0x06, 0x43, 0x36, 0x9c, 0x48, 0x2f, 0xf6, 0xc4, 0x01,
	0x63, 0xbc, 0x49, 0x38, 0xf8, 0x07, 0x56, 0xe3, 0x95, 0xac, 0x74, 0x90, 0x46, 0xec, 0xd6, 0xdd,
	0x6d, 0x13, 0x7f, 0x81, 0xff, 0xd5, 0x5f, 0x61, 0xf6, 0xa3, 0x04, 0x4c, 0x4f, 0x9d, 0xf7, 0xda,
	0x79, 0xef, 0xf5, 0x0d, 0xa0, 0xa8, 0xcc, 0x61, 0xa9, 0x49, 0xd5, 0xf9, 0x8e, 0x96, 0xa5, 0x92,
	0x46, 0x62, 0xcf, 0x3d, 0x92, 0x7b, 0x18, 0x6d, 0x2a, 0x73, 0xe0, 0xf4, 0x55, 0x91, 0x36, 0x88,
	0xd0, 0xad, 0x34, 0x29, 0x16, 0x2d, 0xa2, 0x74, 0xc8, 0xdd, 0x6c, 0xb9, 0x52, 0x68, 0xcd, 0x3a,
	0x9e, 0xb3, 0x73, 0xb2, 0x86, 0xc9, 0xab, 0x38, 0xe6, 0x99, 0x30, 0xb9, 0x2c, 0x9e, 0x94, 0x92,
	0x0a, 0x6f, 0xa0, 0xb7, 0xcf, 0xe9, 0x98, 0x85, 0x5d, 0x0f, 0x70, 0x06, 0x7d, 0xb2, 0xaf, 0xed,
	0x7a, 0x9c, 0x0e, 0x79, 0x40, 0xc9, 0x6f, 0x04, 0x63, 0x6f, 0xac, 0x4b, 0x59, 0x68, 0xb2, 0x2e,
	0x3b, 0x99, 0x91, 0xdb, 0x8e, 0xb9, 0x9b, 0xed, 0xb2, 0x36, 0xc2, 0x54, 0x8d, 0x77, 0x40, 0xd6,
	0xca, 0xc8, 0x0f, 0x2a, 0x58, 0xbc, 0x88, 0xd2, 0x31, 0xf7, 0xc0, 0x2a, 0x98, 0xef, 0x92, 0x58,
	0xd7, 0xe7, 0xb4, 0x33, 0x32, 0x18, 0x7c, 0x92, 0xd6, 0xe2, 0x9d, 0x58, 0xcf, 0xd1, 0x0d, 0xc4,
	0x5b, 0x98, 0x28, 0xda, 0x2b, 0xd2, 0x07, 0xca, 0xb6, 0x5e, 0xad, 0xef, 0xd4, 0xae, 0x4e, 0xf4,
	0x8b, 0x93, 0xdd, 0xc0, 0x75, 0x7d, 0xfa, 0xd5, 0xad, 0x8b, 0xcf, 0x06, 0x8b, 0x38, 0x1d, 0xad,
	0x66, 0xbe, 0xca, 0xe5, 0xbf, 0x26, 0xf8, 0xa4, 0xbe, 0x24, 0x92, 0x47, 0x98, 0x72, 0x2f, 0xea,
	0x24, 0x9b, 0xb2, 0x5b, 0x22, 0x74, 0xda, 0x22, 0xac, 0x7e, 0x22, 0x7f, 0xa5, 0x67, 0x7f, 0x41,
	0x7c, 0xf0, 0xdd, 0x51, 0x61, 0xf2, 0x9d, 0x30, 0x84, 0x18, 0x82, 0x9c, 0x5d, 0x72, 0x3e, 0xbd,
	0xe0, 0x42, 0xc9, 0x6b, 0x18, 0x9f, 0x07, 0xc1, 0x79, 0xf8, 0xa8, 0x25, 0x5d, 0xab, 0xc0, 0x5b,
	0xdf, 0x71, 0x77, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x44, 0xa0, 0x92, 0x52, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/proto.AuthService/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*AuthResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Authenticate(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedAuthServiceServer) RefreshToken(ctx context.Context, req *RefreshTokenRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AuthService_Authenticate_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.service.proto",
}
