// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Result               []byte   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AuthenticateRequest struct {
	Token                []byte   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*AuthenticateRequest)(nil), "proto.AuthenticateRequest")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0x4d, 0x0a, 0xc2, 0x40,
	0x0c, 0x05, 0x60, 0xc6, 0xfe, 0xa8, 0xa1, 0xab, 0x51, 0x64, 0x96, 0xa5, 0xab, 0x82, 0xe0, 0xc6,
	0x13, 0x78, 0x85, 0xdc, 0x60, 0x5a, 0x1f, 0x56, 0xd4, 0x4e, 0x6d, 0x32, 0xf7, 0x17, 0xc7, 0xba,
	0x4a, 0xbe, 0x40, 0x78, 0x8f, 0xa8, 0xf3, 0x82, 0xd3, 0x34, 0x07, 0x0d, 0xb6, 0x48, 0xa3, 0x19,
	0x68, 0xc3, 0x90, 0x29, 0x8c, 0x02, 0x6b, 0x29, 0xef, 0xc3, 0x15, 0xce, 0xd4, 0xa6, 0xcd, 0x38,
	0xed, 0xf6, 0x40, 0xa5, 0xa8, 0xd7, 0x28, 0x6e, 0x55, 0x9b, 0x76, 0xcb, 0x8b, 0xbe, 0xf7, 0x19,
	0x12, 0x9f, 0xea, 0xb2, 0xda, 0xb4, 0x15, 0x2f, 0xb2, 0x8e, 0xd6, 0x2f, 0x88, 0xf8, 0x1b, 0x5c,
	0x9e, 0x1e, 0xfe, 0x6c, 0x8e, 0xb4, 0xbb, 0x44, 0x1d, 0x30, 0xea, 0xbd, 0xf7, 0x0a, 0xc6, 0x3b,
	0x42, 0xd4, 0xee, 0xa9, 0xd0, 0xf0, 0xc0, 0x98, 0x52, 0x2b, 0xfe, 0xa1, 0x2b, 0x53, 0xbb, 0xf3,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x4f, 0x37, 0x89, 0xb2, 0x00, 0x00, 0x00,
}
