// Code generated by protoc-gen-go. DO NOT EDIT.
// source: theater.service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	messages "movie.night.ws.server/proto/messages"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAllUserTheatersRequest struct {
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetAllUserTheatersRequest) Reset()         { *m = GetAllUserTheatersRequest{} }
func (m *GetAllUserTheatersRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllUserTheatersRequest) ProtoMessage()    {}
func (*GetAllUserTheatersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06ad5f814da00b4a, []int{0}
}

func (m *GetAllUserTheatersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUserTheatersRequest.Unmarshal(m, b)
}
func (m *GetAllUserTheatersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUserTheatersRequest.Marshal(b, m, deterministic)
}
func (m *GetAllUserTheatersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUserTheatersRequest.Merge(m, src)
}
func (m *GetAllUserTheatersRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllUserTheatersRequest.Size(m)
}
func (m *GetAllUserTheatersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUserTheatersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUserTheatersRequest proto.InternalMessageInfo

func (m *GetAllUserTheatersRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type CreateTheaterRequest struct {
	Theater              *messages.Theater    `protobuf:"bytes,1,opt,name=theater,proto3" json:"theater,omitempty"`
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,2,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateTheaterRequest) Reset()         { *m = CreateTheaterRequest{} }
func (m *CreateTheaterRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTheaterRequest) ProtoMessage()    {}
func (*CreateTheaterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06ad5f814da00b4a, []int{1}
}

func (m *CreateTheaterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTheaterRequest.Unmarshal(m, b)
}
func (m *CreateTheaterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTheaterRequest.Marshal(b, m, deterministic)
}
func (m *CreateTheaterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTheaterRequest.Merge(m, src)
}
func (m *CreateTheaterRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTheaterRequest.Size(m)
}
func (m *CreateTheaterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTheaterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTheaterRequest proto.InternalMessageInfo

func (m *CreateTheaterRequest) GetTheater() *messages.Theater {
	if m != nil {
		return m.Theater
	}
	return nil
}

func (m *CreateTheaterRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type UserTheatersResponse struct {
	Code                 int64               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string              `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string              `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               []*messages.Theater `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UserTheatersResponse) Reset()         { *m = UserTheatersResponse{} }
func (m *UserTheatersResponse) String() string { return proto.CompactTextString(m) }
func (*UserTheatersResponse) ProtoMessage()    {}
func (*UserTheatersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06ad5f814da00b4a, []int{2}
}

func (m *UserTheatersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTheatersResponse.Unmarshal(m, b)
}
func (m *UserTheatersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTheatersResponse.Marshal(b, m, deterministic)
}
func (m *UserTheatersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTheatersResponse.Merge(m, src)
}
func (m *UserTheatersResponse) XXX_Size() int {
	return xxx_messageInfo_UserTheatersResponse.Size(m)
}
func (m *UserTheatersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTheatersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserTheatersResponse proto.InternalMessageInfo

func (m *UserTheatersResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserTheatersResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UserTheatersResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserTheatersResponse) GetResult() []*messages.Theater {
	if m != nil {
		return m.Result
	}
	return nil
}

type UserTheaterResponse struct {
	Code                 int64             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               *messages.Theater `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserTheaterResponse) Reset()         { *m = UserTheaterResponse{} }
func (m *UserTheaterResponse) String() string { return proto.CompactTextString(m) }
func (*UserTheaterResponse) ProtoMessage()    {}
func (*UserTheaterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06ad5f814da00b4a, []int{3}
}

func (m *UserTheaterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTheaterResponse.Unmarshal(m, b)
}
func (m *UserTheaterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTheaterResponse.Marshal(b, m, deterministic)
}
func (m *UserTheaterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTheaterResponse.Merge(m, src)
}
func (m *UserTheaterResponse) XXX_Size() int {
	return xxx_messageInfo_UserTheaterResponse.Size(m)
}
func (m *UserTheaterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTheaterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserTheaterResponse proto.InternalMessageInfo

func (m *UserTheaterResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserTheaterResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UserTheaterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserTheaterResponse) GetResult() *messages.Theater {
	if m != nil {
		return m.Result
	}
	return nil
}

type TheaterMembersResponse struct {
	Code                 int64            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Result               []*messages.User `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TheaterMembersResponse) Reset()         { *m = TheaterMembersResponse{} }
func (m *TheaterMembersResponse) String() string { return proto.CompactTextString(m) }
func (*TheaterMembersResponse) ProtoMessage()    {}
func (*TheaterMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06ad5f814da00b4a, []int{4}
}

func (m *TheaterMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TheaterMembersResponse.Unmarshal(m, b)
}
func (m *TheaterMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TheaterMembersResponse.Marshal(b, m, deterministic)
}
func (m *TheaterMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TheaterMembersResponse.Merge(m, src)
}
func (m *TheaterMembersResponse) XXX_Size() int {
	return xxx_messageInfo_TheaterMembersResponse.Size(m)
}
func (m *TheaterMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TheaterMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TheaterMembersResponse proto.InternalMessageInfo

func (m *TheaterMembersResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TheaterMembersResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TheaterMembersResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TheaterMembersResponse) GetResult() []*messages.User {
	if m != nil {
		return m.Result
	}
	return nil
}

type AddOrRemoveMemberRequest struct {
	MemberId             string               `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	TheaterId            string               `protobuf:"bytes,2,opt,name=theater_id,json=theaterId,proto3" json:"theater_id,omitempty"`
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,3,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AddOrRemoveMemberRequest) Reset()         { *m = AddOrRemoveMemberRequest{} }
func (m *AddOrRemoveMemberRequest) String() string { return proto.CompactTextString(m) }
func (*AddOrRemoveMemberRequest) ProtoMessage()    {}
func (*AddOrRemoveMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06ad5f814da00b4a, []int{5}
}

func (m *AddOrRemoveMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrRemoveMemberRequest.Unmarshal(m, b)
}
func (m *AddOrRemoveMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrRemoveMemberRequest.Marshal(b, m, deterministic)
}
func (m *AddOrRemoveMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrRemoveMemberRequest.Merge(m, src)
}
func (m *AddOrRemoveMemberRequest) XXX_Size() int {
	return xxx_messageInfo_AddOrRemoveMemberRequest.Size(m)
}
func (m *AddOrRemoveMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrRemoveMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrRemoveMemberRequest proto.InternalMessageInfo

func (m *AddOrRemoveMemberRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *AddOrRemoveMemberRequest) GetTheaterId() string {
	if m != nil {
		return m.TheaterId
	}
	return ""
}

func (m *AddOrRemoveMemberRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

type GetTheaterMembersRequest struct {
	TheaterId            string               `protobuf:"bytes,2,opt,name=theater_id,json=theaterId,proto3" json:"theater_id,omitempty"`
	AuthRequest          *AuthenticateRequest `protobuf:"bytes,3,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetTheaterMembersRequest) Reset()         { *m = GetTheaterMembersRequest{} }
func (m *GetTheaterMembersRequest) String() string { return proto.CompactTextString(m) }
func (*GetTheaterMembersRequest) ProtoMessage()    {}
func (*GetTheaterMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06ad5f814da00b4a, []int{6}
}

func (m *GetTheaterMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTheaterMembersRequest.Unmarshal(m, b)
}
func (m *GetTheaterMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTheaterMembersRequest.Marshal(b, m, deterministic)
}
func (m *GetTheaterMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTheaterMembersRequest.Merge(m, src)
}
func (m *GetTheaterMembersRequest) XXX_Size() int {
	return xxx_messageInfo_GetTheaterMembersRequest.Size(m)
}
func (m *GetTheaterMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTheaterMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTheaterMembersRequest proto.InternalMessageInfo

func (m *GetTheaterMembersRequest) GetTheaterId() string {
	if m != nil {
		return m.TheaterId
	}
	return ""
}

func (m *GetTheaterMembersRequest) GetAuthRequest() *AuthenticateRequest {
	if m != nil {
		return m.AuthRequest
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAllUserTheatersRequest)(nil), "proto.GetAllUserTheatersRequest")
	proto.RegisterType((*CreateTheaterRequest)(nil), "proto.CreateTheaterRequest")
	proto.RegisterType((*UserTheatersResponse)(nil), "proto.UserTheatersResponse")
	proto.RegisterType((*UserTheaterResponse)(nil), "proto.UserTheaterResponse")
	proto.RegisterType((*TheaterMembersResponse)(nil), "proto.TheaterMembersResponse")
	proto.RegisterType((*AddOrRemoveMemberRequest)(nil), "proto.AddOrRemoveMemberRequest")
	proto.RegisterType((*GetTheaterMembersRequest)(nil), "proto.GetTheaterMembersRequest")
}

func init() { proto.RegisterFile("theater.service.proto", fileDescriptor_06ad5f814da00b4a) }

var fileDescriptor_06ad5f814da00b4a = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0x26, 0x66, 0xed, 0x9a, 0xb7, 0xeb, 0x2e, 0xce, 0xae, 0x25, 0xce, 0xb2, 0x58, 0x7a, 0x10,
	0x45, 0x88, 0xb0, 0x1e, 0x65, 0xc1, 0xe0, 0xa1, 0x2c, 0x28, 0x4a, 0xd4, 0x8b, 0x97, 0x92, 0x76,
	0x1e, 0xb6, 0xd0, 0x34, 0x75, 0x66, 0x52, 0x3c, 0x7b, 0xd0, 0x5f, 0xe0, 0xcf, 0xf0, 0x3f, 0x4a,
	0x66, 0xde, 0xa4, 0x69, 0x93, 0x22, 0x95, 0xed, 0xa9, 0x9d, 0x6f, 0xbe, 0xef, 0xcd, 0xf7, 0x5e,
	0xbe, 0x07, 0x0f, 0xf5, 0x04, 0x53, 0x8d, 0x32, 0x52, 0x28, 0x97, 0xd3, 0x31, 0x46, 0x0b, 0x99,
	0xeb, 0x9c, 0xdd, 0x35, 0x3f, 0x1c, 0x46, 0xa9, 0x22, 0x88, 0x77, 0x33, 0x54, 0x2a, 0xfd, 0x8a,
	0xea, 0x85, 0x93, 0x58, 0xfc, 0xac, 0xc2, 0x0b, 0xe5, 0xc0, 0xfe, 0x17, 0x78, 0x34, 0x40, 0x1d,
	0xcf, 0x66, 0x9f, 0x15, 0xca, 0x4f, 0x96, 0xaf, 0x12, 0xfc, 0x56, 0xa0, 0xd2, 0xec, 0x1a, 0x8e,
	0xd3, 0x42, 0x4f, 0x86, 0xd2, 0x9e, 0x43, 0xaf, 0xe7, 0x3d, 0x3d, 0xba, 0xe2, 0x56, 0x1a, 0xc5,
	0x85, 0x9e, 0xe0, 0x5c, 0x4f, 0xc7, 0xa9, 0x46, 0x52, 0x24, 0x47, 0x25, 0x9f, 0x0e, 0xfd, 0x1f,
	0x1e, 0x9c, 0xbf, 0x91, 0x65, 0x49, 0x2a, 0xec, 0xea, 0x3e, 0x87, 0x43, 0xb2, 0x46, 0x25, 0x1f,
	0x44, 0xce, 0x5b, 0xe4, 0xa8, 0x8e, 0xd1, 0x30, 0x71, 0x67, 0x37, 0x13, 0xbf, 0x3c, 0x38, 0x5f,
	0xef, 0x4d, 0x2d, 0xf2, 0xb9, 0x42, 0xc6, 0xe0, 0x60, 0x9c, 0x0b, 0x34, 0x0e, 0xfc, 0xc4, 0xfc,
	0x67, 0x5d, 0xe8, 0x28, 0x9d, 0xea, 0x42, 0x99, 0x57, 0x82, 0x84, 0x4e, 0x2c, 0x84, 0x43, 0x32,
	0x18, 0xfa, 0xe6, 0xc2, 0x1d, 0xd9, 0x33, 0xe8, 0x48, 0x54, 0xc5, 0x4c, 0x87, 0x07, 0x3d, 0xbf,
	0xbd, 0x13, 0x22, 0xf4, 0x7f, 0x7a, 0x70, 0x56, 0x73, 0xb2, 0x47, 0x23, 0xde, 0x3f, 0x8d, 0x74,
	0x09, 0x7b, 0x87, 0xd9, 0xe8, 0xf6, 0x87, 0xf2, 0x64, 0x63, 0x28, 0x27, 0x2b, 0x2f, 0xe5, 0x00,
	0x2a, 0x23, 0xbf, 0x3d, 0x08, 0x63, 0x21, 0xde, 0xcb, 0x04, 0xb3, 0x7c, 0x89, 0xd6, 0x8c, 0x0b,
	0xc9, 0x05, 0x04, 0x99, 0x01, 0x86, 0x53, 0x61, 0xfc, 0x04, 0xc9, 0x3d, 0x0b, 0xdc, 0x08, 0x76,
	0x09, 0x40, 0xf9, 0x28, 0x6f, 0xad, 0xaf, 0x80, 0x90, 0x1b, 0xd1, 0xc8, 0x8c, 0xbf, 0x5b, 0x66,
	0xbe, 0x43, 0x38, 0x40, 0xbd, 0x39, 0x22, 0x6b, 0x6b, 0xaf, 0x2f, 0x5f, 0xfd, 0xf1, 0xe1, 0x84,
	0xde, 0xfd, 0x68, 0xf7, 0x9c, 0x7d, 0x80, 0xd3, 0x01, 0xea, 0x7a, 0x84, 0x59, 0x8f, 0xca, 0x6d,
	0xdd, 0x5c, 0x7e, 0x41, 0x8c, 0xd6, 0xe4, 0xbf, 0x02, 0x58, 0xb5, 0xc7, 0x9a, 0x41, 0xe1, 0xbc,
	0xa9, 0xae, 0xc4, 0xd7, 0x70, 0x7f, 0x6d, 0xa7, 0x99, 0x7b, 0xaa, 0x6d, 0xd3, 0xf9, 0x29, 0x5d,
	0xd6, 0xe4, 0x41, 0x2c, 0x84, 0x9d, 0x29, 0x7b, 0xec, 0xc6, 0xb2, 0x25, 0x03, 0x4d, 0xf9, 0x6b,
	0x38, 0xae, 0xf3, 0xfe, 0xa3, 0xc2, 0x5b, 0xd3, 0x3c, 0x7d, 0xd4, 0x4a, 0xbf, 0xed, 0x73, 0xf3,
	0x4b, 0x22, 0xb4, 0xef, 0xcb, 0xa8, 0x63, 0x6e, 0x5f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xe5,
	0xe9, 0xb5, 0xca, 0x9e, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TheaterServiceClient is the client API for TheaterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TheaterServiceClient interface {
	GetUserTheaters(ctx context.Context, in *GetAllUserTheatersRequest, opts ...grpc.CallOption) (*UserTheatersResponse, error)
	GetTheater(ctx context.Context, in *messages.Theater, opts ...grpc.CallOption) (*UserTheaterResponse, error)
	CreateTheater(ctx context.Context, in *CreateTheaterRequest, opts ...grpc.CallOption) (*Response, error)
	AddMember(ctx context.Context, in *AddOrRemoveMemberRequest, opts ...grpc.CallOption) (*Response, error)
	RemoveMember(ctx context.Context, in *AddOrRemoveMemberRequest, opts ...grpc.CallOption) (*Response, error)
	GetMembers(ctx context.Context, in *GetTheaterMembersRequest, opts ...grpc.CallOption) (*TheaterMembersResponse, error)
}

type theaterServiceClient struct {
	cc *grpc.ClientConn
}

func NewTheaterServiceClient(cc *grpc.ClientConn) TheaterServiceClient {
	return &theaterServiceClient{cc}
}

func (c *theaterServiceClient) GetUserTheaters(ctx context.Context, in *GetAllUserTheatersRequest, opts ...grpc.CallOption) (*UserTheatersResponse, error) {
	out := new(UserTheatersResponse)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/GetUserTheaters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) GetTheater(ctx context.Context, in *messages.Theater, opts ...grpc.CallOption) (*UserTheaterResponse, error) {
	out := new(UserTheaterResponse)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/GetTheater", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) CreateTheater(ctx context.Context, in *CreateTheaterRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/CreateTheater", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) AddMember(ctx context.Context, in *AddOrRemoveMemberRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/AddMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) RemoveMember(ctx context.Context, in *AddOrRemoveMemberRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/RemoveMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *theaterServiceClient) GetMembers(ctx context.Context, in *GetTheaterMembersRequest, opts ...grpc.CallOption) (*TheaterMembersResponse, error) {
	out := new(TheaterMembersResponse)
	err := c.cc.Invoke(ctx, "/proto.TheaterService/GetMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TheaterServiceServer is the server API for TheaterService service.
type TheaterServiceServer interface {
	GetUserTheaters(context.Context, *GetAllUserTheatersRequest) (*UserTheatersResponse, error)
	GetTheater(context.Context, *messages.Theater) (*UserTheaterResponse, error)
	CreateTheater(context.Context, *CreateTheaterRequest) (*Response, error)
	AddMember(context.Context, *AddOrRemoveMemberRequest) (*Response, error)
	RemoveMember(context.Context, *AddOrRemoveMemberRequest) (*Response, error)
	GetMembers(context.Context, *GetTheaterMembersRequest) (*TheaterMembersResponse, error)
}

// UnimplementedTheaterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTheaterServiceServer struct {
}

func (*UnimplementedTheaterServiceServer) GetUserTheaters(ctx context.Context, req *GetAllUserTheatersRequest) (*UserTheatersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTheaters not implemented")
}
func (*UnimplementedTheaterServiceServer) GetTheater(ctx context.Context, req *messages.Theater) (*UserTheaterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTheater not implemented")
}
func (*UnimplementedTheaterServiceServer) CreateTheater(ctx context.Context, req *CreateTheaterRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTheater not implemented")
}
func (*UnimplementedTheaterServiceServer) AddMember(ctx context.Context, req *AddOrRemoveMemberRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMember not implemented")
}
func (*UnimplementedTheaterServiceServer) RemoveMember(ctx context.Context, req *AddOrRemoveMemberRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMember not implemented")
}
func (*UnimplementedTheaterServiceServer) GetMembers(ctx context.Context, req *GetTheaterMembersRequest) (*TheaterMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembers not implemented")
}

func RegisterTheaterServiceServer(s *grpc.Server, srv TheaterServiceServer) {
	s.RegisterService(&_TheaterService_serviceDesc, srv)
}

func _TheaterService_GetUserTheaters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUserTheatersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).GetUserTheaters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/GetUserTheaters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).GetUserTheaters(ctx, req.(*GetAllUserTheatersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_GetTheater_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(messages.Theater)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).GetTheater(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/GetTheater",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).GetTheater(ctx, req.(*messages.Theater))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_CreateTheater_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTheaterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).CreateTheater(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/CreateTheater",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).CreateTheater(ctx, req.(*CreateTheaterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrRemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/AddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).AddMember(ctx, req.(*AddOrRemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrRemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/RemoveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).RemoveMember(ctx, req.(*AddOrRemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TheaterService_GetMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTheaterMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TheaterServiceServer).GetMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TheaterService/GetMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TheaterServiceServer).GetMembers(ctx, req.(*GetTheaterMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TheaterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TheaterService",
	HandlerType: (*TheaterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserTheaters",
			Handler:    _TheaterService_GetUserTheaters_Handler,
		},
		{
			MethodName: "GetTheater",
			Handler:    _TheaterService_GetTheater_Handler,
		},
		{
			MethodName: "CreateTheater",
			Handler:    _TheaterService_CreateTheater_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _TheaterService_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _TheaterService_RemoveMember_Handler,
		},
		{
			MethodName: "GetMembers",
			Handler:    _TheaterService_GetMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "theater.service.proto",
}
